version: '3.8'

services:
  web:
    volumes:
      - ./web/nginx-longtimeout.conf:/etc/nginx/conf.d/nginx-longtimeout.conf
  app:
    ports:
      - 5678:5678
    # see https://aka.ms/vscode-docker-python-debug
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 app.py --nothreading --noreload"]
