version: '3.8'

services:
  app:
    ports:
      - 5678:5678
    environment:
      - FLASK_DEBUG=True
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 app.py runserver 0.0.0.0:5000 --nothreading --noreload"]
