version: '3.8'

services:
  app:
    logging:
      driver: journald
  web:
    logging:
      driver: journald

  crond:
    logging:
      driver: journald
    volumes:
      - /mnt/backup/db_backup:/backup
