version: '3.8'

services:
  app:
    logging:
      driver: journald
  web:
    logging:
      driver: journald
  phpmyadmin:
    logging:
      driver: journald
  db:
    logging:
      driver: journald

  crond:
    volumes:
      - /mnt/backup/db_backup:/backup

secrets:
  db-password:
    file: /home/appuser/.docker/webmodules-db-password.txt
  user-password:
    file: /home/appuser/.docker/webmodules-user-password.txt
