version: "3.8"

services:
  db:
    # https://github.com/docker-library/mysql/issues/275#issuecomment-636831964
    image: mysql:8.0.32 # 8.0.32 gives access denied on centos7 server for both root and user (same for 5.7.41)
    # command: '--default-authentication-plugin=mysql_native_password'
    command: '--default-authentication-plugin=mysql_native_password --log_error_verbosity=3' # mysql
    restart: always
    secrets:
      - db-password
      - user-password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend-network
    environment:
      - MYSQL_DATABASE=webmodules
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
      - MYSQL_USER=user
      - MYSQL_PASSWORD_FILE=/run/secrets/user-password

  app:
    build: app
    restart: always
    depends_on:
      - db
    secrets:
      - db-password
      - user-password
    networks:
      - backend-network
      - frontend-network

  web:
    build: web
    restart: always
    ports:
      - 8000:80
    networks:
      - frontend-network
    # uncomment to debug
    # command: [nginx-debug, '-g', 'daemon off;']

  phpmyadmin:
    image: phpmyadmin:5.2.1-fpm
    restart: always
    depends_on:
      - db
    networks:
      - backend-network
      - frontend-network
    environment:
      - PMA_ABSOLUTE_URI=http://phpmyadmin/phpmyadmin
    #   - PMA_ARBITRARY=1
    #   - PMA_HOST=db

volumes:
  db-data:

secrets:
  db-password:
    file: db/password.txt
  user-password:
    file: db/userpassword.txt

networks:
  backend-network:
  frontend-network: