version: '3.8'

services:
  app:
    ports:
      - 5678:5678
    volumes:
      - ./app/src:/app
    environment:
      - FLASK_DEBUG=True
  
  web:
    volumes:
      - ./web/nginx.conf.dev:/etc/nginx/conf.d/server.conf:ro
    ports:
      - 8000:80
