version: '3.8'

services:
  web:
    ports:
      - 8000:443
    volumes:
      # - /etc/letsencrypt:/etc/nginx/ssl:ro
      - ./web/nginx.conf.prod:/etc/nginx/conf.d/server.conf:ro

secrets:
  db-password:
    file: /home/appuser/.docker/webmodules-db-password.txt
  user-password:
    file: /home/appuser/.docker/webmodules-user-password.txt
