name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: isbang/compose-action@v1.4.1
        with:
          context: .
          file: ./docker-compose.yaml
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/webmodules:latest
