name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        # https://stackoverflow.com/a/63350136/799921
        name: Create .env file
        # https://github.com/actions/runner/issues/655#issuecomment-886144271
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
          cat .env >> $GITHUB_ENV
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push app
        uses: docker/build-push-action@v4
        with:
          context: ./app
          build-args: |
            PYTHON_VER=$PYTHON_VER
          file: ./app/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/webmodules-app:latest
      -
        name: Build and push web
        uses: docker/build-push-action@v2
        with:
          context: ./web
          build-args: |
            NGINX_VER=$NGINX_VER
            PHPMYADMIN_VER=$PHPMYADMIN_VER
          file: ./web/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/webmodules-web:latest
